---
name: example
label: Example Tile
description: Serves as an example tile >> $( variable "some-variable" )

metadata_version: "2.0"
minimum_version_for_upgrade: 1.12.0
product_version: "0.0.0.0$PRERELEASE_VERSION$"
provides_product_versions:
- name: example
  version: "0.0.0.0$PRERELEASE_VERSION$"

icon_image: $( icon )

rank: 90
serial: false

post_deploy_errands:
- name: my-errand
  label: My Errand
  description: Does things
  colocated: true
  run_default: true
  instances:
  - my-instance-group/first

releases:
- $( release "my-release" )

stemcell_criteria: $( stemcell )

runtime_configs:
- $( runtime_config "my-runtime-config" )

property_blueprints:
- $( property "element_1" )
- $( property "element_2" )

form_types:
- $( form "first" )

job_types:
- $( instance_group "my-instance-group" )
