---
name: example
label: Example Tile
description: Serves as an example tile

metadata_version: '2.0'
minimum_version_for_upgrade: 1.12.0
product_version: "0.0.0.0$PRERELEASE_VERSION$"
provides_product_versions:
- name: example
  version: "0.0.0.0$PRERELEASE_VERSION$"

rank: 90
serial: false

post_deploy_errands:
- name: my-errand
  label: My Errand
  description: Does things
  colocated: true
  run_default: true
  instances:
  - my-instance/first

property_blueprints:
- name: element_1
  type: text
  configurable: true
  optional: true

- name: element_2
  type: text
  configurable: true
  optional: false
