---
name: example
label: Example Tile
description: Serves as an example tile

metadata_version: '2.0'
minimum_version_for_upgrade: 1.12.0
product_version: "0.0.0.0$PRERELEASE_VERSION$"
provides_product_versions:
- name: example
  version: "0.0.0.0$PRERELEASE_VERSION$"

rank: 90
serial: false

post_deploy_errands:
- name: my-errand
  label: My Errand
  description: Does things
  colocated: true
  run_default: true
  instances:
  - my-instance/first

property_blueprints:
- name: element_1
  type: text
  configurable: true
  optional: true

- name: element_2
  type: text
  configurable: true
  optional: false

job_types:
- name: my-instance
  label: My Instance
  resource_label: My Instance
  description: This is an instance.

  templates:
  - name: my-job
    release: my-release
    manifest: |
      job-properties:
        example: "example"
  - name: my-errand
    release: my-release
    manifest: |
      errand-properties:
        example: "example"

  static_ip: 1
  dynamic_ip: 0

  max_in_flight: 1
  single_az_only: true

  instance_definition:
    name: instances
    type: integer
    label: Instances
    configurable: true
    default: 1
    constraints:
      min: 0
      max: 1

  resource_definitions:
  - name: ram
    type: integer
    label: RAM
    configurable: true
    default: 1024
    constraints:
      min: 1024

  - name: ephemeral_disk
    type: integer
    label: Ephemeral Disk
    configurable: true
    default: 4000
    constraints:
      min: 2000

  - name: persistent_disk
    type: integer
    label: Persistent Disk
    configurable: false
    default: 200000
    constraints:
      min: 10000

  - name: cpu
    type: integer
    label: CPU
    configurable: true
    default: 1
    constraints:
      min: 1
